spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 20
      minimumIdle: 10
      autoCommit: true
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO
    root: INFO
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs

#server:
#  servlet:
#    context-path: /hotel-booking